version: '3.8'

services:
  ccap-app:
    build: 
      context: ..
      dockerfile: docker/Dockerfile.flask
    container_name: ccap-flask-app
    restart: unless-stopped
    networks:
      - ccap-network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    volumes:
      - ../logs:/app/logs
    expose:
      - "5000"

  nginx:
    image: nginx:alpine
    container_name: ccap-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      # add port 443 when doing HTTPS
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/sites-available:/etc/nginx/sites-available:ro
      - ../nginx/proxy_params:/etc/nginx/proxy_params:ro
      - /var/www/certbot:/var/www/certbot  # for webroot challenges
      - /etc/letsencrypt:/etc/letsencrypt:ro  # for SSL certs
    networks:
      - ccap-network
    depends_on:
      - ccap-app 

networks:
  ccap-network:
    driver: bridge