name: Deploy to AWS VM then SonarQube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to AWS EC2 via SSH
      uses: appleboy/ssh-action@master  
      with:
        host: 18.220.138.198
        username: limited_student
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          cd /opt/ccap/ICT2216-Group1-CCAPortal/
          git pull origin main
          cd docker
          docker-compose -f nginx-compose.yml down
          docker-compose -f nginx-compose.yml up -d --build

  sonarqube:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: DNS check
        run: nslookup ccap-sonar.domloh.com

      - name: Single SonarQube connectivity check
        run: |
          echo "Checking SonarQube once..."
          curl -sSf "${{ secrets.SONAR_HOST_URL }}/api/system/status"
          echo "Waiting 30 seconds for stability..."
          sleep 30

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}