name: Basic CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create test config for CI
      run: |
        cat > config.py << EOF
        # Test Configuration for CI
        DB_SERVER = "test-server"
        DB_NAME = "test-db"
        DB_USERNAME = "test-user"
        DB_PASSWORD = "test-password"
        DB_CONNECTION_STRING = "test-connection-string"
        SECRET_KEY = "test-secret-key-for-ci-only"
        EOF
    
    - name: Test app can import
      run: |
        python -c "print('Testing if app can import...'); import app; print('App imported successfully')"
    
    - name: Show success message
      run: |
        echo "🎉 First CI/CD pipeline is working"
        echo "✅ Code checked out"
        echo "✅ Python set up" 
        echo "✅ Dependencies installed"
        echo "✅ App can import successfully"