name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/github_deploy_key
        chmod 600 ~/.ssh/github_deploy_key
        ssh-keyscan -H 18.220.138.198 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh student1@18.220.138.198 << 'EOF'
          cd /home/student1/ICT2216-Group1-CCAPortal  # Replace with your actual folder
          git pull origin main
          docker compose -f docker/nginx-compose.yml down
          docker compose -f docker/nginx-compose.yml up --build -d
        EOF
