name: Flask UI + Unit Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DB_CONN_STRING: ${{ secrets.DB_CONN_STRING }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Microsoft ODBC Driver 18 for SQL Server
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-add-repository "$(curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list)"
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Create config.py with encoded connection string
        run: |
          cat <<EOF > config.py
          import os
          import urllib.parse

          class Config:
              raw_odbc = os.getenv("DB_CONN_STRING")
              if not raw_odbc:
                  raise ValueError("❌ Missing DB_CONN_STRING")

              SQLALCHEMY_DATABASE_URI = "mssql+pyodbc:///?odbc_connect=" + urllib.parse.quote_plus(raw_odbc)
              SQLALCHEMY_TRACK_MODIFICATIONS = False
              SECRET_KEY = os.getenv("SECRET_KEY", "fallback")
          EOF

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Start Flask App
        run: |
          nohup python app.py &
          sleep 5

      - name: Wait for Flask to respond
        run: |
          for i in {1..10}; do
            echo "Checking Flask..."
            curl -s http://localhost:5000/health && break || sleep 3
          done

      - name: Run Unit Tests
        run: pytest tests/test_login.py

      - name: Check Flask Logs
        if: always()
        run: |
          echo "==== Flask Log (nohup.out) ===="
          cat nohup.out || echo "No nohup.out file found"
