name: Flask UI + Unit Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TESTING: "1"
      FLASK_ENV: "development"
      DB_SERVER: ${{ secrets.DB_SERVER }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Microsoft ODBC Driver 18 for SQL Server
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo apt-add-repository "$(curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list)"
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Create secure config.py from secrets
        run: |
          cat <<'EOF' > config.py
          import os

          class Config:
              SQLALCHEMY_DATABASE_URI = 'sqlite:///:memory:'  # fallback or test
              SQLALCHEMY_TRACK_MODIFICATIONS = False

              DB_SERVER = os.getenv("DB_SERVER")
              DB_NAME = os.getenv("DB_NAME")
              DB_USERNAME = os.getenv("DB_USERNAME")
              DB_PASSWORD = os.getenv("DB_PASSWORD")
              SECRET_KEY = os.getenv("SECRET_KEY")

              if SECRET_KEY is None:
                  raise ValueError("❌ SECRET_KEY not set!")

              DB_CONNECTION_STRING = (
                  f"DRIVER={{ODBC Driver 18 for SQL Server}};"
                  f"SERVER={DB_SERVER};"
                  f"DATABASE={DB_NAME};"
                  f"UID={DB_USERNAME};"
                  f"PWD={DB_PASSWORD};"
                  f"Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;"
              )
          EOF

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Start Flask App
        run: |
          nohup python app.py &
          sleep 5

      - name: Wait for Flask to respond
        run: |
          for i in {1..10}; do
            echo "Checking Flask..."
            curl -s http://localhost:5000/health && break || sleep 3
          done

      - name: Run Unit Tests
        run: pytest tests/test_login.py
