name: Security Check

on:
  push:
    branches: [ main ]
  schedule:
    # Run security checks daily at 2 AM SGT (6 PM UTC)
    - cron: '0 18 * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit pip-audit
    
    - name: Install project dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run Safety check (dependency vulnerabilities)
      run: |
        echo "Checking for known security vulnerabilities in dependencies..."
        safety check --json --output safety-report.json
        safety check  

    - name: Run Bandit check (code security issues)
      run: |
        echo "Scanning code for security issues..."
        bandit -r . -f json -o bandit-report.json
        bandit -r . -ll  

    - name: Run pip-audit (additional dependency check)
      run: |
        echo "Running additional dependency vulnerability scan..."
        pip-audit --format=json --output=pip-audit-report.json
        pip-audit  
    
    - name: Security scan completed
      run: |
        echo "Security scanning completed"
        echo "Check the logs above for any security findings"
        echo "Regular security scanning helps keep your app secure"