name: Flask UI + Unit Testing (Selenium)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    env:
      TESTING: "1"
      FLASK_ENV: "development"

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 🧠 Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        
      - name: 📦 Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest selenium

      - name: 🚀 Start Flask App
        run: |
          nohup python app.py &
          sleep 5

      - name: ✅ Run Unit Tests
        run: pytest tests/test_login.py

      - name: 🧪 Run Selenium UI Tests
        run: pytest tests/test_login_ui.py
