name: ZAP Scan on Live Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  zap_scan:
    name: Live ZAP Baseline Scan
    runs-on: ubuntu-latest

    steps:
      - name: Check if site is online
        run: |
          echo "Checking availability of site..."
          curl -I http://18.220.138.198 || exit 1

      - name: Run ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.14.0
        env:
          ZAP_DISABLE_SAVE: true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://18.220.138.198'
          cmd_options: ''
          artifact_name: zap-report-public-${{ github.run_id }}
